name: Build LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t latex-pdf-generator .

      - name: Run LaTeX compilation
        id: compile_latex
        run: |
          mkdir -p ./output
          docker run --rm -v $(pwd)/output:/workspace/output latex-pdf-generator

      - name: Check if PDF was generated
        run: |
          if [ ! -f ./output/main.pdf ]; then
            echo "PDF generation failed"
            exit 1
          fi

      - name: Rename PDF
        run: mv ./output/main.pdf ./output/pedro_ramos_diehl_vitae.pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        uses: actions/upload-artifact@v4
        with:
          name: pedro_ramos_diehl_vitae.pdf
          path: ./output/pedro_ramos_diehl_vitae.pdf
          retention_days: 30

      - name: Attach PDF to Release
        uses: softprops/attach-artifacts@v1
        with:
          artifacts: pedro_ramos_diehl_vitae.pdf
          target: ${{ steps.create_release.outputs.upload_url }}
