name: Build and Generate PDF

on:
  push:
    branches:
      - main

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t pdf-generator .

      - name: Run Docker container and generate PDF
        id: generate_pdf
        run: |
          docker run -d --name pdf-container pdf-generator sleep infinity
          docker wait pdf-container

      - name: Copy main.pdf from Docker container
        run: docker cp pdf-container:/workspace/main.pdf ./main.pdf

      - name: Upload main.pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: ./main.pdf

      - name: Clean up
        if: always()
        run: docker rm pdf-container
