name: Build LaTeX Document

on:
  push:
    tags:
      - "v*"

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t latex-pdf-generator .

      - name: Run LaTeX compilation
        id: compile_latex
        run: |
          mkdir -p ./output
          docker run --rm -v $(pwd)/output:/workspace/output latex-pdf-generator

      - name: Check if PDF was generated
        run: |
          if [ ! -f ./output/main.pdf ]; then
            echo "PDF generation failed"
            exit 1
          fi

      - name: Rename PDF
        run: mv ./output/main.pdf ./output/pedro_ramos_diehl_vitae.pdf

      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Curriculum ${tag#v}" \
              --generate-notes

      - name: Upload Release Asset
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} ./output/pedro_ramos_diehl_vitae.pdf
