name: Build LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t latex-pdf-generator .

      - name: Run LaTeX compilation
        id: compile_latex
        run: |
          mkdir -p ./output
          docker run --rm -v $(pwd)/output:/workspace/output latex-pdf-generator

      - name: Check if PDF was generated
        run: |
          if [ ! -f ./output/main.pdf ]; then
            echo "PDF generation failed"
            exit 1
          fi

      - name: Upload main.pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: ./output/main.pdf
