name: Build and Run Dockerfile

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: optimus

    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Run Docker container
        run: docker run --rm my-docker-image sleep 15

      - name: Copy main.pdf from Docker container
        run: docker cp $(docker ps -ql):/path/to/main.pdf ./main.pdf

      - name: Upload main.pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: ./main.pdf
